// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/monitoring.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	NetworkIn     float64                `protobuf:"fixed64,3,opt,name=network_in,json=networkIn,proto3" json:"network_in,omitempty"`
	NetworkOut    float64                `protobuf:"fixed64,4,opt,name=network_out,json=networkOut,proto3" json:"network_out,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_api_proto_monitoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_api_proto_monitoring_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *Metric) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *Metric) GetNetworkIn() float64 {
	if x != nil {
		return x.NetworkIn
	}
	return 0
}

func (x *Metric) GetNetworkOut() float64 {
	if x != nil {
		return x.NetworkOut
	}
	return 0
}

func (x *Metric) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PushMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMetricsRequest) Reset() {
	*x = PushMetricsRequest{}
	mi := &file_api_proto_monitoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMetricsRequest) ProtoMessage() {}

func (x *PushMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMetricsRequest.ProtoReflect.Descriptor instead.
func (*PushMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_monitoring_proto_rawDescGZIP(), []int{1}
}

func (x *PushMetricsRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type PushMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMetricsResponse) Reset() {
	*x = PushMetricsResponse{}
	mi := &file_api_proto_monitoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMetricsResponse) ProtoMessage() {}

func (x *PushMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMetricsResponse.ProtoReflect.Descriptor instead.
func (*PushMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_monitoring_proto_rawDescGZIP(), []int{2}
}

func (x *PushMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushMetricsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_monitoring_proto protoreflect.FileDescriptor

const file_api_proto_monitoring_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/monitoring.proto\x12\n" +
	"monitoring\"\xa6\x01\n" +
	"\x06Metric\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x01R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"network_in\x18\x03 \x01(\x01R\tnetworkIn\x12\x1f\n" +
	"\vnetwork_out\x18\x04 \x01(\x01R\n" +
	"networkOut\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"B\n" +
	"\x12PushMetricsRequest\x12,\n" +
	"\ametrics\x18\x01 \x03(\v2\x12.monitoring.MetricR\ametrics\"I\n" +
	"\x13PushMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2c\n" +
	"\x11MonitoringService\x12N\n" +
	"\vPushMetrics\x12\x1e.monitoring.PushMetricsRequest\x1a\x1f.monitoring.PushMetricsResponseB$Z\"github.com/stupidrun/mon/api/protob\x06proto3"

var (
	file_api_proto_monitoring_proto_rawDescOnce sync.Once
	file_api_proto_monitoring_proto_rawDescData []byte
)

func file_api_proto_monitoring_proto_rawDescGZIP() []byte {
	file_api_proto_monitoring_proto_rawDescOnce.Do(func() {
		file_api_proto_monitoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_monitoring_proto_rawDesc), len(file_api_proto_monitoring_proto_rawDesc)))
	})
	return file_api_proto_monitoring_proto_rawDescData
}

var file_api_proto_monitoring_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_monitoring_proto_goTypes = []any{
	(*Metric)(nil),              // 0: monitoring.Metric
	(*PushMetricsRequest)(nil),  // 1: monitoring.PushMetricsRequest
	(*PushMetricsResponse)(nil), // 2: monitoring.PushMetricsResponse
}
var file_api_proto_monitoring_proto_depIdxs = []int32{
	0, // 0: monitoring.PushMetricsRequest.metrics:type_name -> monitoring.Metric
	1, // 1: monitoring.MonitoringService.PushMetrics:input_type -> monitoring.PushMetricsRequest
	2, // 2: monitoring.MonitoringService.PushMetrics:output_type -> monitoring.PushMetricsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_monitoring_proto_init() }
func file_api_proto_monitoring_proto_init() {
	if File_api_proto_monitoring_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_monitoring_proto_rawDesc), len(file_api_proto_monitoring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_monitoring_proto_goTypes,
		DependencyIndexes: file_api_proto_monitoring_proto_depIdxs,
		MessageInfos:      file_api_proto_monitoring_proto_msgTypes,
	}.Build()
	File_api_proto_monitoring_proto = out.File
	file_api_proto_monitoring_proto_goTypes = nil
	file_api_proto_monitoring_proto_depIdxs = nil
}
